#!/usr/bin/env python3
"""
Generate a valid 15x15 crossword puzzle.
Uses system dictionary solver, then outputs complete validated JSON.
"""

import json
import sys
import time
import random
from collections import defaultdict

PATTERN = [
    "....#....#.....",
    "....#....#.....",
    "....#....#.....",
    "###.....#......",
    ".....##....####",
    "...#......#....",
    ".......#.......",
    ".......#.......",
    ".......#.......",
    "....#......#...",
    "####....##.....",
    "......#.....###",
    ".....#....#....",
    ".....#....#....",
    ".....#....#....",
]

slots = []
for r in range(15):
    c = 0
    while c < 15:
        if PATTERN[r][c] == '.':
            s = c
            while c < 15 and PATTERN[r][c] == '.': c += 1
            if c-s >= 3:
                slots.append(('A', [(r, s+i) for i in range(c-s)]))
        else: c += 1
for col in range(15):
    r = 0
    while r < 15:
        if PATTERN[r][col] == '.':
            s = r
            while r < 15 and PATTERN[r][col] == '.': r += 1
            if r-s >= 3:
                slots.append(('D', [(s+i, col) for i in range(r-s)]))
        else: r += 1

print(f"Total slots: {len(slots)}")

# Load ALL words from system dict (lowercase only, no proper nouns)
all_words = set()
with open("/usr/share/dict/words") as f:
    for line in f:
        w = line.strip()
        if w.isalpha() and w.islower() and 3 <= len(w) <= 7:
            all_words.add(w.upper())

# Common words to strongly prefer
COMMON = set()
common_text = """
ACE ACT ADD AGE AGO AID AIM AIR ALE ALL AND ANT APE ARC ARE ARK ARM ART ASH ATE AWE AXE
BAD BAG BAN BAR BAT BAY BED BET BIG BIT BOW BOX BOY BUD BUG BUN BUS BUT BUY
CAB CAN CAP CAR CAT COB COD COG COP COT COW CRY CUB CUD CUP CUR CUT
DAB DAD DAM DAY DEN DEW DID DIG DIM DIN DIP DOC DOG DOT DRY DUB DUD DUE DUG DUN DUO DYE
EAR EAT EEL EGG ELF ELK ELM EMU END ERA EVE EWE EYE
FAN FAR FAT FAX FED FEW FIG FIN FIR FIT FIX FLU FLY FOB FOE FOG FOP FOR FOX FRY FUN FUR
GAB GAG GAP GAS GEL GEM GET GIG GIN GNU GOB GOD GOT GUM GUN GUT GUY GYM
HAD HAM HAS HAT HAW HAY HEN HER HEW HID HIM HIP HIT HOB HOD HOG HOP HOT HOW HUB HUE HUG HUM HUT
ICE ICY ILL IMP INK INN ION IRE IRK ITS IVY JAB JAG JAM JAR JAW JAY JET JIG JOB JOG JOT JOY JUG JUT
KEG KEN KEY KID KIN KIT LAB LAD LAG LAP LAW LAX LAY LEA LED LEG LET LID LIE LIP LIT LOG LOT LOW LUG
MAD MAN MAP MAR MAT MAW MAX MAY MEN MET MID MIX MOB MOD MOM MOP MOW MUD MUG MUM
NAB NAG NAP NET NEW NIL NIT NOB NOD NOR NOT NOW NUB NUN NUT OAF OAK OAR OAT ODD ODE OIL OLD ONE OPT ORB ORE OUR OUT OWE OWL OWN
PAD PAN PAP PAR PAT PAW PAY PEA PEG PEN PEP PER PET PEW PIE PIG PIN PIT PLY POD POP POT POW PRY PUB PUG PUN PUP PUT
RAG RAM RAN RAP RAT RAW RAY RED REF RIB RID RIG RIM RIP ROB ROD ROT ROW RUB RUG RUM RUN RUT RYE
SAD SAG SAP SAT SAW SAY SEA SET SEW SHE SHY SIN SIP SIR SIS SIT SIX SKI SKY SLY SOB SOD SON SOP SOW SOY SPA SPY STY SUB SUM SUN SUP
TAB TAD TAG TAN TAP TAR TAT TAX TEA TEN THE TIE TIN TIP TOE TON TOO TOP TOT TOW TOY TRY TUB TUG TUN TWO URN USE VAN VAT VET VIA VIE VOW
WAD WAG WAR WAS WAX WAY WEB WED WET WHO WIG WIN WIT WOE WOK WON WOO WOW YAK YAM YAP YAW YEA YES YET YEW YOU ZAP ZEN ZIP ZOO
BEE BOO COO DIM FEE GEE HEE REV RUE SOB TEE WEE WHO WHY WOE
ABLE ACHE ACID ACRE AGED AIDE AIDS AIMS AIRY AKIN ALSO AMID ANKH ARCH AREA ARIA ARMY ARTS ASKS ATOM AUTO AVID AXIS
BABY BACK BADE BAGS BAIL BAIT BAKE BALD BALE BALL BAND BANE BANG BANK BARE BARK BARN BASE BASH BASS BATH BATS BAYS BEAD BEAK BEAM BEAN BEAR BEAT BEDS BEEF BEEN BEER BEES BELL BELT BEND BENT BEST BETS BIKE BILL BIND BIRD BITE BLEW BLOW BLUE BLUR BOAR BOAT BODY BOLD BOLT BOMB BOND BONE BOOK BOOM BOOT BORE BORN BOSS BOTH BOUT BOWL BOWS BOYS BRAN BRED BREW BRIM BROW BUCK BUDS BUGS BULB BULK BULL BUMP BURN BURY BUSH BUSY BUTT BUZZ
CAFE CAGE CAKE CALF CALL CALM CAME CAMP CANE CAPE CAPS CARD CARE CARP CARS CART CASE CASH CAST CAVE CELL CHEF CHIN CHIP CHOP CITE CITY CLAD CLAM CLAN CLAP CLAW CLAY CLEF CLIP CLOD CLOT CLUB CLUE COAL COAT COCK CODE COIL COIN COLD COLT COMB COME CONE COOK COOL COPE CORD CORE CORK CORN COST COUP COVE COWL CRAB CRAM CREW CRIB CROP CROW CUBE CUBS CULT CUPS CURB CURE CURL CURT CUTE CUTS
DABS DALE DAME DAMP DAMS DARE DARK DARN DART DASH DATA DATE DAWN DAYS DAZE DEAD DEAF DEAL DEAR DECK DEED DEEM DEEP DEER DEMO DENT DENY DESK DICE DIED DIGS DIME DINE DIRE DIRT DISC DISH DOCK DOES DOGS DOLE DOME DONE DOOM DOOR DOSE DOTS DOWN DOZE DRAB DRAG DRAM DRAW DREW DRIP DROP DRUM DUAL DUCK DUDE DUEL DUES DUET DUKE DULL DUMB DUMP DUNE DUNG DUNK DUPE DUSK DUST DUTY DYED DYES
EACH EARL EARN EARS EASE EAST EASY EATS ECHO EDGE EDGY EDIT EELS EGGS ELSE EMIT ENDS EPIC EVEN EVER EVIL EXAM EXEC EXIT EYED EYES
FACE FACT FADE FAIL FAIR FAKE FALL FAME FANG FANS FARE FARM FAST FATE FAWN FAZE FEAR FEAT FEED FEEL FEES FEET FELL FELT FEND FERN FEST FEUD FIGS FILE FILL FILM FIND FINE FIRE FIRM FISH FIST FITS FIVE FLAG FLAN FLAP FLAT FLAW FLEA FLED FLEW FLIP FLIT FLOG FLOP FLOW FLUE FOAM FOES FOIL FOLD FOLK FOND FONT FOOD FOOL FOOT FORD FORE FORK FORM FORT FOUL FOUR FOWL FRAY FREE FROG FROM FUEL FULL FUME FUND FURY FUSE FUSS FUZZ
GAIT GALE GALL GAME GANG GAPE GAPS GARB GASH GASP GATE GAVE GAZE GEAR GENE GERM GETS GIFT GILD GILT GIST GIVE GLAD GLEN GLIB GLOW GLUE GLUM GNAW GOAD GOAL GOAT GODS GOES GOLD GOLF GONE GOOD GORE GORY GOWN GRAB GRAM GRAY GREW GRID GRIM GRIN GRIP GRIT GROW GRUB GULF GULL GUMS GUNG GUNS GUSH GUST GUTS GUYS
HACK HAIL HAIR HALE HALF HALL HALT HAMS HAND HANG HARE HARK HARM HARP HASH HATE HAUL HAVE HAWK HAZE HAZY HEAD HEAL HEAP HEAR HEAT HEED HEEL HELD HELM HELP HEMP HENS HERE HERD HERO HEWN HIDE HIGH HIKE HILL HILT HIND HINT HIPS HIRE HISS HIVE HOLD HOLE HOME HONE HOOD HOOF HOOK HOOP HOPE HOPS HORN HOSE HOST HOUR HOWL HUBS HUED HUES HUGE HUGS HULL HUMP HUMS HUNG HUNK HUNT HURL HURT HUSK HUTS HYMN
ICED IDEA IDLE IDOL INCH INNS IOTA IRIS IRON ISLE ITCH ITEM
JABS JADE JAIL JAMS JARS JAWS JAZZ JEAN JEER JERK JEST JETS JILT JOBS JOCK JOGS JOIN JOKE JOLT JOSH JOTS JOWL JOYS JUGS JUMP JUNE JUNK JURY JUST JUTE
KALE KEEN KEEP KEGS KELP KEPT KEYS KICK KIDS KILL KIND KING KINK KITE KITS KNEE KNEW KNIT KNOB KNOT KNOW
LACE LACK LACY LADS LAID LAKE LAMB LAME LAMP LAND LANE LAPS LARD LARK LASH LASS LAST LATE LAWN LAWS LAZY LEAD LEAF LEAK LEAN LEAP LEER LEFT LEGS LEND LENS LENT LESS LEST LIAR LICE LICK LIDS LIED LIEN LIES LIFE LIFT LIKE LILY LIMB LIME LIMP LINE LINK LINT LION LIPS LIST LIVE LOAD LOAF LOAM LOAN LOBE LOCK LODE LOFT LOGO LOGS LONE LONG LOOK LOOM LOOP LOOT LORD LORE LORN LOSE LOSS LOST LOTS LOUD LOVE LOWS LUCK LULL LUMP LURE LURK LUSH LUST
MACE MADE MAID MAIL MAIN MAKE MALE MALL MALT MANE MANY MAPS MARE MARK MARS MASH MASK MASS MAST MATE MATH MAZE MEAD MEAL MEAN MEAT MEEK MEET MELD MELT MEMO MEND MENU MERE MESH MESS MICE MILD MILE MILK MILL MIME MIND MINE MINI MINT MIRE MISS MIST MITE MITT MOAN MOAT MOCK MODE MOLD MOLE MOLT MONK MOOD MOON MOOR MOPE MOPS MORE MORN MOSS MOST MOTH MOVE MUCH MUCK MUDS MUFF MUGS MULE MULL MUSE MUSH MUSK MUST MUTE MUTT
NABS NAGS NAIL NAME NAPE NAPS NAVE NAVY NEAR NEAT NECK NEED NERD NEST NETS NEWS NEXT NICE NICK NINE NODE NONE NOON NORM NOSE NOTE NOUN NUDE NUMB NUNS NUTS
OAFS OAKS OARS OATH OATS OBEY ODDS ODES ODOR OILS OILY OKAY OMEN OMIT ONCE ONES ONLY ONTO OOZE OPAL OPEN OPTS ORAL ORES OURS OUST OUTS OVEN OVER OWED OWES OWLS OWNS
PACE PACK PACT PADS PAGE PAID PAIL PAIN PAIR PALE PALM PALS PANE PANG PANS PARE PARK PART PASS PAST PATH PAVE PAWN PAWS PAYS PEAK PEAL PEAR PEAS PEAT PECK PEEL PEEP PEER PEGS PELT PEND PENS PENT PERK PERM PERT PEST PETS PICK PIES PILE PILL PINE PINK PINS PINT PIPE PITS PITY PLAN PLAY PLEA PLOD PLOT PLOW PLOY PLUG PLUM PLUS POCK POEM POET POKE POLE POLL POLO POMP POND PONY POOL POOR POPE POPS PORE PORK PORT POSE POST POUR POUT PRAY PREP PREY PRIM PROD PROP PROW PUBS PUCK PUFF PULL PULP PUMP PUNS PUNK PUPS PURE PUSH PUTS PUTT
RACE RACK RAFT RAGE RAGS RAID RAIL RAIN RAKE RAMP RAMS RANG RANK RANT RAPS RASH RASP RATE RATS RAVE RAYS RAZE READ REAL REAM REAP REAR REED REEF REEK REEL REIN RELY REND RENT REST RIBS RICE RICH RIDE RIFT RIGS RILE RIME RIMS RIND RING RINK RIPE RISE RISK RITE ROAD ROAM ROAR ROBE ROBS ROCK RODE ROLE ROLL ROMP ROOF ROOM ROOT ROPE ROSE ROSY ROTE ROTS ROUT ROVE ROWS RUBS RUDE RUED RUES RUGS RUIN RULE RUMP RUMS RUNE RUNG RUNS RUNT RUSE RUSH RUST RUTS
SACK SAFE SAGE SAGS SAID SAIL SAKE SALE SALT SAME SAND SANE SANG SANK SASH SAVE SAWS SAYS SCAB SCAM SCAN SCAR SEAL SEAM SEAR SEAS SEAT SEED SEEK SEEM SEEN SEEP SEER SELF SELL SEMI SEND SENT SEPT SERF SETS SEWN SHED SHIN SHIP SHOE SHOO SHOP SHOT SHOW SHUN SHUT SICK SIDE SIFT SIGH SIGN SILK SILL SILT SINE SING SINK SIPS SIRE SIRS SITE SITS SIZE SKID SKIM SKIN SKIP SKIT SLAB SLAG SLAM SLAP SLAT SLAW SLED SLEW SLID SLIM SLIT SLOB SLOE SLOG SLOP SLOT SLOW SLUG SLUM SLUR SMOG SNAP SNOB SNUB SNUG SOAK SOAP SOAR SOBS SOCK SODA SOFA SOFT SOIL SOLD SOLE SOLO SOME SONG SONS SOON SOOT SORE SORT SOUL SOUR SPAN SPAR SPAS SPEC SPED SPIN SPIT SPOT SPUR STAB STAG STAR STAY STEM STEP STEW STIR STOP STOW STUB STUD STUN SUBS SUCH SUIT SULK SUMS SUNG SUNK SUNS SURE SURF SWAP SWAN SWAY SWIM
TABS TACK TACT TAGS TAIL TAKE TALE TALK TALL TAME TAMP TANG TANK TAPE TAPS TARN TART TASK TAXI TEAK TEAL TEAM TEAR TEAS TEEM TELL TEMP TEND TENS TENT TERM TERN TEST TEXT THAN THAT THEM THEN THEY THIN THIS THUS TICK TIDE TIDY TIED TIES TILE TILL TILT TIME TINE TINS TINY TIRE TOAD TOED TOES TOIL TOLD TOLL TOMB TOME TONE TONS TOOK TOOL TOPS TORE TORN TORT TOSS TOUR TOUT TOWN TOYS TRAP TRAY TREE TREK TRIM TRIO TRIP TROD TROT TRUE TUBA TUBE TUBS TUCK TUFT TUGS TUNA TUNE TURF TURN TUSK TUTU TWIN TYPE
UGLY UNDO UNIT UNTO UPON URGE URNS USED USER USES VAIN VALE VANE VANS VARY VASE VAST VATS VEAL VEER VEIL VEIN VENT VERB VERY VEST VETO VIAL VICE VIED VIES VIEW VILE VINE VISA VOID VOLE VOLT VOTE VOWS
WADE WADS WAGE WAIL WAIT WAKE WALK WALL WAND WANE WANT WARD WARM WARN WARP WARS WART WARY WASH WASP WAVE WAVY WAXY WAYS WEAK WEAN WEAR WEBS WEDS WEED WEEK WEEP WELD WELL WENT WEPT WERE WEST WHAT WHEN WHIM WHIP WHOM WICK WIDE WIFE WILD WILE WILL WILT WILY WIMP WIND WINE WING WINK WINS WIPE WIRE WISE WISP WISH WITH WITS WOES WOKE WOLF WOMB WONT WOOD WOOL WORD WORE WORK WORM WORN WOVE WRAP WREN
YAKS YAMS YANK YAPS YARD YARN YAWL YAWN YAWS YEAR YELL YELP YOGA YOUR YOWL ZANY ZEAL ZERO ZEST ZINC ZING ZONE ZOOM ZOOS
ABATE ABBEY ABBOT ABHOR ABIDE ABOUT ABOVE ABUSE ACHED ACORN ACTED ACUTE ADAPT ADDED ADEPT ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE AHEAD AIDED AIMED AISLE ALARM ALBUM ALERT ALIEN ALIGN ALIKE ALIVE ALLEY ALLOT ALLOW ALOFT ALONE ALONG ALOOF ALTER AMAZE AMBLE AMEND AMPLE AMUSE ANGEL ANGER ANGLE ANGRY ANKLE ANNEX ANTIC APART APPLY ARENA ARGUE ARISE ARMOR AROMA AROSE ARRAY ARROW ASCOT ASIDE ASSET ATTIC AUDIO AUDIT AVOID AWAKE AWARD AWARE AWFUL
BADGE BADLY BAGEL BAKER BANDS BANKS BARON BASED BASES BASIC BASIN BASIS BATCH BATHE BEANS BEARS BEAST BEATS BEGIN BEGUN BEING BELOW BENCH BERRY BIBLE BIKES BIRDS BIRTH BLACK BLADE BLAME BLAND BLANK BLAST BLAZE BLEAK BLEED BLEND BLESS BLIND BLINK BLISS BLITZ BLOCK BLOND BLOOD BLOOM BLOWN BLOWS BLUFF BLUNT BLURT BLUSH BOARD BOAST BOATS BOLTS BONDS BONES BONUS BOOKS BOOTS BORED BORNE BOUND BOWED BOWEL BOXER BRACE BRAIN BRAND BRASS BRAVE BREAD BREAK BREED BRICK BRIDE BRIEF BRING BRINK BRISK BROAD BROKE BROOK BROTH BROWN BRUSH BUILD BUILT BULGE BUNCH BURNT BURST
CABIN CABLE CAMEL CANDY CARGO CARRY CATCH CATER CAUSE CEASE CEDAR CHAIN CHAIR CHALK CHAMP CHANT CHAOS CHARM CHART CHASE CHEAP CHEAT CHECK CHEEK CHEER CHESS CHEST CHILD CHILL CHINA CHIPS CHORD CHOSE CHUNK CIGAR CIVIC CIVIL CLAIM CLAMP CLANG CLANK CLASH CLASP CLASS CLEAN CLEAR CLERK CLICK CLIFF CLIMB CLING CLOAK CLOCK CLONE CLOSE CLOTH CLOUD CLOWN CLUBS CLUMP CLUNG COACH COAST COATS COBRA COLOR COMIC CORAL COULD COUNT COURT COVER CRACK CRAFT CRANE CRASH CRATE CRAVE CRAWL CRAZE CRAZY CREAK CREAM CREEP CREST CREWS CRIME CRISP CROOK CROPS CROSS CROWD CROWN CRUDE CRUEL CRUSH CURVE CYCLE
DAILY DAIRY DANCE DARTS DEALT DEATH DEBUT DECAY DECOY DEEDS DELAY DELTA DENSE DEPOT DEPTH DERBY DEVIL DIGIT DINER DIRTY DISCO DITCH DIVER DIZZY DODGE DOING DONOR DOUBT DOUGH DRAFT DRAIN DRAKE DRAMA DRANK DRAPE DRAWN DRAWS DREAD DREAM DRESS DRIED DRIFT DRILL DRINK DRIVE DRONE DROOL DROPS DROWN DRUGS DRUMS DRUNK DWARF DWELL DYING
EAGER EAGLE EARLY EARTH EASED EATEN EIGHT ELBOW ELDER ELECT ELITE EMBED EMBER EMPTY ENDOW ENEMY ENJOY ENTER ENTRY EQUAL EQUIP ERODE ERROR ERUPT ESSAY EVENT EVERY EVICT EVOKE EXACT EXALT EXCEL EXERT EXILE EXIST EXTRA
FABLE FACET FACTS FAILS FAINT FAIRY FAITH FALSE FANCY FATAL FAULT FEAST FEATS FENCE FERRY FETCH FEVER FIBER FIELD FIEND FIERY FIFTH FIFTY FIGHT FILED FILES FILTH FINAL FINDS FIRST FIXED FLAME FLANK FLAPS FLARE FLASH FLASK FLATS FLESH FLIES FLING FLINT FLOAT FLOCK FLOOD FLOOR FLORA FLOUR FLOWN FLOWS FLUID FLUKE FLUSH FLUTE FOCAL FOCUS FOGGY FOLKS FORCE FORGE FORMS FORTH FORUM FOUND FOXES FRAIL FRAME FRANK FRAUD FREED FRESH FRONT FROST FROZE FRUIT FULLY FUNNY FUZZY
GAUGE GAUNT GIANT GIVEN GIVES GLAND GLARE GLASS GLEAM GLIDE GLOBE GLOOM GLORY GLOSS GLOVE GNOME GODLY GOING GOODS GOOSE GORGE GRACE GRADE GRAIN GRAND GRANT GRAPE GRASP GRASS GRATE GRAVE GRAVY GRAZE GREED GREEN GREET GRIEF GRILL GRIND GRIPE GROAN GROIN GROOM GROPE GROSS GROUP GROVE GROWL GROWN GROWS GRUFF GRUNT GUARD GUESS GUEST GUIDE GUILD GUILT GUISE GULLS GUSTY
HABIT HANDS HANDY HAPPY HARDY HASTE HASTY HATCH HAUNT HAVEN HEADS HEARD HEART HEAVY HEDGE HEELS HEIRS HERBS HERDS HILLS HILLY HINGE HINTS HITCH HOBBY HOLDS HOLES HOMER HOMES HONEY HONOR HOOKS HOPED HOPES HORNS HORSE HOSTS HOTEL HOTLY HOUND HOURS HOUSE HUMAN HUMOR HUNTS HURRY HYENA HYMNS
IDEAL IMAGE IMPLY INDEX INNER INPUT IRONY ISSUE IVORY JEWEL JOINT JUICE JUMBO KAYAK KNACK KNAVE KNEEL KNELT KNIFE KNOCK KNOWN KNOWS
LABEL LABOR LADEN LADLE LANCE LANDS LANES LARGE LASER LATCH LATER LATHE LAUGH LAYER LEADS LEAKY LEAPS LEARN LEASE LEAST LEAVE LEGAL LEMON LEVEL LEVER LIGHT LILAC LIMBS LIMIT LINED LINEN LINER LINES LINKS LIONS LISTS LITER LIVED LIVER LOADS LOAFS LOANS LOBBY LOCAL LODGE LOFTY LOGIC LOOKS LOOSE LORDS LOUSY LOVED LOVER LOVES LOWER LOYAL LUCKY LUMPS LUNAR LUNCH LUNGE LYING
MAGIC MANOR MAPLE MARCH MASON MATCH MAYBE MAYOR MEALS MEANS MEANT MEDIA MELON MERCY MERGE MERIT MERRY METAL METER MIDST MIGHT MILES MILLS MIMIC MINCE MINDS MINER MINOR MINUS MIRTH MISER MODEL MOIST MONEY MONTH MOOSE MORAL MOTEL MOTHS MOTOR MOTTO MOUND MOUNT MOURN MOUSE MOUTH MOVED MOVER MOVES MOVIE MOWED MUDDY MULES MUSIC MYTHS
NAIVE NAMED NAMES NANNY NASAL NASTY NAVAL NERVE NEWER NEWLY NIGHT NOBLE NODAL NODES NOISE NOISY NORTH NOTCH NOTED NOTES NOVEL NURSE
OASIS OCCUR OCEAN OFFER OFTEN OLIVE ONSET ORDER ORGAN OTHER OUTER OVALS OVENS OXIDE OWNER
PACED PACES PACKS PAGES PAINS PAINT PAIRS PANEL PANIC PANTS PAPER PARKS PARTY PASTE PATCH PATHS PAUSE PEACE PEACH PEAKS PEARL PEARS PEDAL PEELS PENNY PERCH PERIL PERKS PETAL PHASE PHONE PHOTO PIANO PICKS PIECE PILED PILES PILLS PILOT PINCH PINES PIPES PITCH PLACE PLAID PLAIN PLANE PLANK PLANS PLANT PLATE PLAZA PLEAD PLEAS PLEAT PLIED PLOTS PLOWS PLUCK PLUGS PLUMB PLUME PLUMP PLUMS PLUNK PLUSH POETS POINT POISE POKER POLAR POLES POLKA POLLS PONDS POOLS PORCH PORES PORTS POSED POSES POSTS POUCH POUND POURS POWER PRANK PRAWN PRESS PRICE PRIDE PRIME PRINT PRIOR PRISM PRIZE PROBE PRONG PRONE PROOF PROSE PROUD PROVE PRUNE PSALM PULLS PULSE PUMPS PUNCH PUPIL PURSE PUSHY QUEST QUICK QUIET QUILT QUIRK QUOTA QUOTE
RADAR RAISE RALLY RANCH RANGE RANKS RAPID RATES RATIO RAZOR REACH READS REALM REBEL REEDS REIGN REINS RELAX RELAY REMIT REPLY RESIN RIDER RIDGE RIFLE RIGHT RIGID RINDS RINGS RINSE RISEN RISES RISKS RISKY RIVAL RIVER ROADS ROAMS ROAST ROBES ROBOT ROCKS ROCKY ROLES ROLLS ROOMS ROOTS ROPES ROSES ROTOR ROUGH ROUND ROUTE ROVER ROYAL RUINS RULED RULER RULES RURAL RUSTY
SADLY SAINT SALAD SALES SALTY SALVE SANDY SAUCE SAUNA SAVED SCALE SCARE SCARF SCENE SCENT SCOPE SCORE SCOUT SCRAP SEEDS SEIZE SENSE SERVE SHADE SHAFT SHALL SHAME SHAPE SHARE SHARK SHARP SHAWL SHEAR SHEDS SHEER SHELL SHIFT SHINE SHINY SHIRT SHOCK SHONE SHOOK SHORE SHORT SHOUT SHOVE SHOWN SHOWS SHRUB SIDES SIEGE SIGHT SIGMA SIGNS SILLY SINCE SIREN SITES SIXTH SIXTY SIZED SIZES SKATE SKILL SKINS SKIPS SKIRT SKULL SLATE SLAVE SLEEP SLEET SLICE SLIDE SLOPE SLOTH SLUGS SMALL SMART SMELL SMILE SMOKE SNACK SNAKE SNARE SNEAK SNIDE SOLID SOLVE SONIC SORRY SOUTH SPACE SPARE SPARK SPAWN SPEAK SPEAR SPEED SPELL SPEND SPENT SPICE SPICY SPIED SPIKE SPILL SPINE SPOKE SPOON SPORT SPOTS SPRAY SQUAD STACK STAFF STAGE STAIN STAIR STAKE STALE STALK STALL STAMP STAND STANK STARE STARK START STATE STAYS STEAK STEAL STEAM STEEL STEEP STEER STEMS STEPS STERN STICK STIFF STILL STING STINT STOCK STOLE STOMP STONE STOOD STOOL STOOP STORE STORM STORY STOUT STOVE STRAP STRAW STRAY STRIP STUCK STUDY STUFF STUMP STUNG STUNT STYLE SUGAR SUITE SUNNY SUPER SURGE SWAMP SWEAR SWEAT SWEEP SWEET SWEPT SWIFT SWING SWIPE SWIRL SWORD SWORE SWORN SWUNG
TABLE TACIT TAILS TAKEN TAKES TALES TALKS TAMED TANGS TANKS TAPES TARDY TASKS TASTE TEASE TEETH TEMPO TENSE TERMS TESTS THEME THERE THICK THIEF THIGH THING THINK THIRD THORN THOSE THREE THREW THROW THUMB TIDAL TIERS TIGER TIGHT TILES TIMER TIMES TIPSY TIRED TITLE TOAST TODAY TOKEN TOLLS TONAL TONED TONES TOOLS TORCH TOTAL TOUGH TOURS TOWEL TOWER TOWNS TOXIC TRACE TRACK TRADE TRAIL TRAIN TRAIT TRAPS TRASH TRAWL TREAD TREAT TREES TREND TRIAL TRIBE TRICK TRIED TRIMS TRIPS TROOP TROUT TRUCE TRUCK TRULY TRUMP TRUNK TRUST TRUTH TUBES TULIP TUMOR TUNED TUNER TUNES TURNS TUTOR TWEED TWICE TWIGS TWINS TWIRL TWIST TYPED TYPES
ULCER ULTRA UNDER UNDUE UNION UNITE UNITY UNTIL UPPER UPSET URBAN USHER USING USUAL UTTER
VAGUE VALID VALUE VALVE VAPOR VAULT VERSE VIDEO VIGOR VINYL VIOLA VIPER VIRUS VISIT VISOR VITAL VIVID VOCAL VODKA VOICE VOTER VOUCH VOWEL
WAGES WAGON WAIST WALKS WALLS WALTZ WASTE WATCH WATER WAVES WEARY WEAVE WEDGE WEEDS WEEKS WEIGH WEIRD WELLS WHEAT WHEEL WHERE WHICH WHILE WHINE WHIRL WHISK WHITE WHOLE WHOSE WIDER WIDTH WINGS WIRED WIRES WITCH WOMEN WOODS WORDS WORLD WORRY WORSE WORST WORTH WOULD WOUND WRAPS WRATH WRING WRIST WRITE WRONG WROTE
YACHT YEARS YEAST YIELD YOUNG YOUTH ZONES
ABSORB ACCENT ACCEPT ACCESS ACCORD ACCUSE ACROSS ACTING ACTION ACTIVE ACTUAL ADDING ADJUST ADMIRE ADMITS ADULTS ADVENT ADVISE AFFAIR AFFIRM AFFORD AFRAID AGENCY AGENDA AGENTS AGREED AIMING ALMOST ALWAYS AMOUNT ANCHOR ANNUAL ANSWER ANYWAY APPEAL APPEAR ARCHED ARCTIC ARGUED AROUND ARREST ARRIVE ARTIST ASCEND ASKING ASPECT ASSERT ASSESS ASSIGN ASSIST ASSUME ASSURE ATTACH ATTACK ATTAIN ATTEND AUTHOR AVENUE AVOIDS AWAKEN
BACKED BACKUP BADGES BADGER BAILED BAKERY BALLOT BANANA BANDED BANDIT BANISH BANKER BANNED BANNER BARELY BARLEY BARREN BARREL BASKET BATTEN BATTER BATTLE BEACON BEAKER BEATEN BEAUTY BECOME BEFORE BEGINS BEHALF BEHAVE BEHIND BELONG BETTER BEYOND BITTER BLANCH BLANKS BLEACH BLOCKS BLOODY BLOUSE BOARDS BOASTS BODIES BOLTED BONDED BONNET BOOKED BORDER BORROW BOTHER BOTTLE BOTTOM BOUNCE BOUNDS BRANCH BRANDS BREACH BREAKS BREEZE BRICKS BRIDGE BRIGHT BRINGS BROKEN BROKER BRONZE BROWSE BRUISE BRUTAL BUBBLE BUCKET BUCKLE BUDGET BUFFET BUILDS BULLET BUNDLE BUNKER BURDEN BUREAU BURIAL BURNED BURNER BUTTER BUTTON BUYING
CABANA CABINS CANCEL CANCER CANDLE CANOPY CANYON CARBON CAREER CARING CARPET CARVED CASUAL CATTLE CAUGHT CAUSED CAUSES CAVITY CEASED CELLAR CEMENT CENTER CHAINS CHAIRS CHANCE CHANGE CHAPEL CHARGE CHARTS CHASED CHEEKS CHEERS CHEESE CHOICE CHOSEN CHUNKS CHURCH CIRCLE CITIES CLAIMS CLAMPS CLASSY CLEANS CLEARS CLEVER CLIENT CLIMAX CLINIC CLOCKS CLOSED CLOSER CLOSET CLOUDS CLOVER CLUMSY COARSE COBALT COFFEE COFFIN COLLAR COLONY COLUMN COMBAT COMEDY COMING COMMON CONVEY COOKED COOKIE COOLER COPIES COPPER CORNER COSTLY COTTON COUNTS COUNTY COUPLE COUPON COURSE COURTS COUSIN COVERS COWARD CRADLE CRAFTS CRATER CRAVED CRAYON CREAKY CREAMY CREATE CREDIT CREEPS CRISIS CRISPY CRITIC CROWDS CRUISE CRUTCH CURVED CUSTOM CYCLES
DABBLE DAGGER DAINTY DAMAGE DAMPEN DANCER DANGER DANGLE DARING DARKEN DASHED DEADLY DEALER DEARLY DEATHS DEBATE DEBRIS DECADE DECENT DECIDE DECODE DECREE DEEMED DEEPEN DEEPLY DEFEAT DEFECT DEFEND DEFINE DEGREE DELAYS DELETE DEMAND DEMISE DENOTE DENTAL DEPART DEPEND DEPLOY DEPTHS DEPUTY DERIVE DESERT DESIGN DESIRE DETAIL DETECT DEVISE DEVOTE DEVOUR DIALOG DINNER DIRECT DISARM DISOWN DIVING DOCTOR DOLLAR DOMAIN DONATE DONKEY DOUBLE DOUBTS DRAFTS DRAGON DRAINS DRAPES DRAWER DREAMS DRIVEN DRIVER DRIVES DRONES DUSTER ENABLE
EARNED EARTHS EASILY EATING ECHOED ECHOES EDITED EDITOR EFFECT EFFORT EIGHTH EITHER ELATED ELDEST ELEVEN EMERGE EMPIRE EMPLOY ENABLE ENCORE ENDING ENDURE ENERGY ENGAGE ENGINE ENJOYS ENOUGH ENSURE ENTIRE ENTITY EQUALS ERASED ERRAND ESCAPE ESCORT ESSAYS ESTATE ESTEEM ETHNIC EVENLY EVENTS EVOLVE EXCEED EXCEPT EXCESS EXCITE EXCUSE EXEMPT EXISTS EXPAND EXPECT EXPERT EXPORT EXPOSE EXTEND EXTENT EXTRAS
FABRIC FACIAL FACING FACTOR FADING FAILED FAIRLY FALLEN FAMILY FAMINE FAMOUS FARMER FASTEN FATTEN FAUCET FAULTS FAULTY FELINE FELLOW FEMALE FENDER FERRET FESTER FEUDAL FIDDLE FIERCE FIGHTS FIGURE FILLED FILLER FILTER FINALE FINALS FINDER FINELY FINEST FINGER FINISH FISCAL FISHED FITTED FIXING FLAMES FLARED FLAVOR FLAWED FLEECE FLESHY FLIGHT FLINCH FLINGS FLOATS FLOODS FLOORS FLOPPY FLORAL FLOWED FLOWER FLUENT FLUIDS FLYING FOILED FOLDER FOLDED FOLLOW FONDLY FORCED FOREST FORGED FORGET FORMAL FORMAT FORMER FOSSIL FOSTER FOUGHT FOURTH FRAMED FRAMES FREEZE FRENZY FRIEZE FRINGE FROZEN FRUITS FUMBLE FUNDED FUNNEL FUSION FUTILE FUTURE
GAINED GALLON GAMBIT GAMING GANDER GARAGE GARDEN GARLIC GATHER GENTLE GENTLY GIFTED GIGGLE GIRDLE GIVING GLARED GLOBAL GLOOMY GLOSSY GLOVES GOLDEN GOTTEN GOVERN GRACED GRAINS GRANGE GRANTS GRAPES GRAVEL GRAVES GREASY GREEDY GREETS GRIEVE GRINDS GROUND GROUPS GROUSE GROVES GROWTH GRUDGE GRUMPY GUARDS GUESTS GUIDED GUILTY GUITAR GUTTER
HABITS HALTED HAMLET HAMMER HANDLE HANGAR HAPPEN HARBOR HARDEN HARDER HARDLY HARMED HATRED HAULED HAZARD HEADED HEADER HEALTH HEAPED HEARTS HEATED HEATER HEAVEN HEEDED HEIGHT HELMET HELPED HELPER HERBAL HEROES HEROIC HIDDEN HIDING HIGHLY HIKING HINGES HIRING HOLLOW HOMAGE HONEST HOODED HOOKED HOPING HORDES HORNED HORROR HORSES HOSTED HOSTEL HOURLY HOUSED HOUSES HOWLER HUDDLE HUMBLE HUNGER HUNGRY HUNTED HUNTER HURDLE HURLED HUSHED HUSTLE
IDEALS IGNORE IMAGES IMMUNE IMPACT IMPORT IMPOSE IMPURE INCOME INDEED INDOOR INDUCE INFANT INFORM INJECT INJURY INLAID INLAND INMATE INNATE INSECT INSIDE INSIST INSULT INTACT INTEND INTENT INVADE INVENT INVEST INVITE INWARD IRONED ISLAND ISSUED ITSELF
JABBED JACKET JAGGED JAILED JAUNTY JERSEY JIGSAW JINGLE JOCKEY JOINED JOINTS JOKING JOSTLE JUDGED JUGGLE JUMBLE JUMPED JUNGLE JUNIOR
KERNEL KICKED KIDNEY KILLER KITTEN KNIGHT KNIVES KNOTTY
LABELS LACKED LADDER LAGOON LANDED LANDER LARGER LASTLY LATELY LATEST LAUNCH LAVISH LAYERS LAYING LAYOUT LEADER LEAGUE LEAKED LEANED LEAPED LEASED LENDER LESSEN LESSON LETTER LIFTED LIGHTS LIMBER LINEAR LINERS LINGER LINKED LIQUID LISTED LISTEN LITTER LITTLE LIVELY LOADED LOCKER LOCKED LODGED LONGER LOOKED LOOPED LOOSEN LOSSES LOUNGE LOVELY LOVERS LOVING LOWEST LURING LURKED LUXURY
MADAME MAIDEN MAINLY MAKING MALICE MANAGE MANNER MARBLE MARGIN MARINE MARKED MARKER MARKET MARRED MASKED MASSED MASTER MATTER MEADOW MEDDLE MEDIUM MELODY MEMBER MEMORY MENACE MENTAL MENTOR MERELY MERGED MERGER MERITS MESSED METHOD MIDDLE MIGHTY MILDLY MINDED MINGLE MINING MINUTE MIRROR MISERY MISSED MITTEN MIXING MOANED MOBILE MODERN MODEST MODIFY MOLDED MOLTEN MOMENT MONKEY MONTHS MOORED MORSEL MORTAL MOSAIC MOSTLY MOTHER MOTION MOTIVE MOTORS MOUNTS MOVERS MOVING MUFFIN MURDER MUSCLE MUSEUM MUSTER MUTTER MUTUAL MUZZLE MYSELF MYSTIC
NAMELY NAMING NAPKIN NARROW NATION NATIVE NATURE NEATLY NEEDED NEEDLE NESTED NEURAL NEWEST NICELY NIGHTS NIMBLE NOBLES NODDED NOBODY NORMAL NOTICE NOTION NOVELS NUMBER NURSES
OBJECT OBTAIN OCCUPY OCEANS OFFEND OFFICE OFFSET ONIONS OPENER OPENLY OPERAS OPPOSE OPTION ORACLE ORANGE ORBITS ORDEAL ORDERS ORGANS ORIGIN ORPHAN OTHERS OUTFIT OUTLET OUTPUT OVERLY OWNERS
PACKED PACING PADDLE PAINED PAIRED PALACE PALATE PANELS PAPERS PARADE PARCEL PARENT PARKED PARLOR PARROT PARTLY PASSED PASSES PASTEL PATROL PATRON PAUSED PAYING PEBBLE PEDALS PEELED PEERED PENCIL PEOPLE PEPPER PERIOD PERMIT PERSON PETALS PHRASE PICKED PICKET PICKLE PICNIC PIGEON PILLAR PILLOW PINNED PIRATE PLACED PLACES PLAGUE PLAINS PLANET PLANTS PLATES PLAYED PLAYER PLEASE PLEDGE PLENTY PLOWED PLUNGE PLYING POCKET POETRY POISED POISON POLICE POLISH POLITE POLLED PONDER PONIES POORLY POPLAR POPPED PORTAL POSTED POSTER POTATO POTENT POTION POTTER POUNDS POURED POWDER POWERS PRAISE PRAYER PREFER PRETTY PRICED PRIMED PRINCE PRINTS PRISON PRIZED PROBED PROFIT PROMPT PROPER PROVED PROVEN PRUNES PUBLIC PUDDLE PULLED PULPIT PUMPED PUNISH PUPILS PUPPET PURELY PURSUE PUSHED PUZZLE
RABBIT RACIAL RACKET RADISH RAGGED RAIDED RAISED RANGES RANKED RANSOM RASCAL RATHER RATING RATION RAVAGE RAVING READER REALTY REASON REBORN RECALL RECENT RECIPE RECKON RECORD REDUCE REFORM REFUSE REGARD REGIME REGION REGRET REJECT RELATE RELIED RELIEF RELISH RELOAD REMAIN REMEDY REMIND REMOTE REMOVE RENDER RENTAL REPAID REPAIR REPEAL REPEAT REPENT REPLAY REPORT RESIGN RESIST RESORT RESULT RESUME RETAIL RETAIN RETIRE RETORT RETURN REVEAL REVIEW REVOLT REWARD RIBBON RICHLY RIDDLE RIDGES RIDING RIGHTS RIPPLE RISING RITUAL RIVALS RIVERS ROBUST ROCKED ROCKET RODENT ROLLED ROLLER ROOKIE ROOTED ROTATE ROTTEN ROUNDS ROUTES ROVERS RUBBED RUBBLE RUFFLE RUGGED RUINED RULERS RULING RUMBLE RUNWAY RUSHED RUSTIC RUSTLE
SACRED SADDLE SAFARI SAFELY SAFETY SALARY SALMON SALTED SALUTE SAMPLE SANITY SAVAGE SAVING SCARCE SCARED SCENIC SCHEME SCHOOL SCORED SCORES SCOUTS SCRAPS SCREEN SCROLL SEARCH SEASON SEATED SECRET SECTOR SECURE SEEING SEEMED SEIZED SELECT SELLER SENIOR SENSED SENSES SERIAL SERIES SERMON SERVED SERVER SETTLE SEVERE SEWING SHADOW SHAKEN SHAPED SHAPES SHARED SHARES SHAVED SHEARS SHELLS SHIELD SHIFTS SHINED SHIRTS SHIVER SHOOTS SHORES SHORTS SHOULD SHOUTS SHOWED SHOWER SHREWD SHRINK SHROUD SHRUBS SIGNAL SIGNED SILENT SILVER SIMPLE SIMPLY SINFUL SINGLE SISTER SIZING SKETCH SKILLS SLEEVE SLICED SLIDER SLIGHT SLOGAN SMOOTH SNARLS SNATCH SNOWED SOAKED SOCIAL SOCKET SOLELY SOLEMN SOLVED SOMBER SOUGHT SOUNDS SOURCE SPACES SPARED SPARSE SPEAKS SPEARS SPEECH SPEEDS SPHERE SPICES SPOKEN SPONGE SPORTS SPREAD SPRING SPRINT SPROUT SPURTS SQUARE STABLE STACKS STAGED STAGES STAINS STAIRS STAKES STALLS STANCE STANDS STARCH STARED STARTS STATED STATES STATUS STAYED STEADY STEAKS STEALS STEAMS STEELS STEEPS STEERS STENCH STICKY STIFLE STOCKS STOLEN STOMPS STONES STORED STORES STORMS STORMY STOVES STRAIN STRAND STRAPS STRAWS STREAK STREAM STREET STRESS STRICT STRIDE STRIKE STRING STRIPE STRIPS STRIVE STROKE STROLL STRONG STRUCK STRUNG STUDIO STUMPS STUPID STURDY SUBTLE SUDDEN SUITES SUMMER SUMMIT SUMMON SUNSET SUPERB SUPPLY SURELY SURFER SURVEY SYMBOL SYSTEM
TABLET TACKLE TACTIC TAGGED TAILOR TAKING TALENT TALKED TALLER TANDEM TANGLE TAPPED TARGET TARIFF TASTED TAUGHT TEAPOT TEMPER TENDER TENNIS TENURE TERMED THATCH THEMES THESIS THIEVE THINGS THORNS THORNY THOUGH THREAD THRICE THRIFT THRILL THRIVE THRONE THROWN THROWS THRUST TICKET TILLED TIMBER TINTED TISSUE TITLED TITLES TOASTS TOGGLE TOILET TONGUE TOPICS TOPPED TORQUE TOSSED TOWARD TOWERS TRACED TRACES TRACKS TRADES TRAILS TRAINS TRAITS TRAVEL TREATS TRENDS TRIALS TRIBES TRICKS TRIPLE TROPHY TROUGH TRUANT TRUCKS TRUMPS TRUSTS TUMBLE TUNING TUNNEL TURKEY TURNED TURTLE TWELVE TWENTY TWISTS TYCOON TYPING
UGLIER UNABLE UNBORN UNCLES UNDONE UNFOLD UNFURL UNIONS UNIQUE UNITED UNLIKE UNLOCK UNREST UNSEEN UNTOLD UNUSED UNWRAP UPBEAT UPDATE UPHOLD UPROAR UPSETS UPTURN URGENT USABLE USEFUL UTMOST UTTERS
VACANT VACUUM VALLEY VALUED VALUES VANISH VARIED VARIES VELVET VENDOR VENEER VERBAL VERIFY VERSUS VESSEL VICTIM VIDEOS VIEWED VIEWER VIOLET VIRTUE VISION VISITS VISUAL VOCALS VOLUME VOTING VOYAGE VULGAR
WAFERS WAGERS WAGING WAITED WAITER WAKING WALKED WALKER WALLED WALLET WANDER WANTED WARMED WARMTH WARNED WASTED WATERS WAVING WEAKEN WEALTH WEAPON WEEKLY WEIGHT WIDELY WIELDS WINTER WIRING WISDOM WISHED WISHES WITHIN WONDER WOODEN WORKER WORLDS WORTHY WOUNDS WRECKS WRITER WRITES
YEARLY YIELDS ZEALOT ZIGZAG ZOMBIE ZONING
ABANDON ABILITY ABOLISH ABSENCE ABSOLVE ABSORBS ABSTAIN ACCEPTS ACCLAIM ACCOUNT ACHIEVE ACREAGE ACTIONS ADAPTED ADDRESS ADJOURN ADOPTED ADVANCE ADVERSE ADVISED ADVISOR AFFAIRS AFFECTS AGELESS ALIGNED ALLEGED ALLOWED ALREADY ALTERED AMAZING AMNESIA AMOROUS AMOUNTS AMPLIFY AMUSING ANALYST ANALYZE ANCHORS ANCIENT ANNOYED ANOTHER ANSWERS ANTENNA ANTIQUE ANXIETY ANXIOUS ANYTIME APPAREL APPEALS APPLIED APPOINT APPROVE ARCHERY ARRANGE ARRIVAL ARRIVED ARSENAL ARTICLE ARTISTS ASCENDS ASSAULT ASSUMES ATTRACT AUCTION AUDIBLE AUGMENT AUSTERE AVOCADO AWARDED
BACKERS BACKING BACKLOG BAGGAGE BALANCE BALLOON BANKING BARGAIN BARRIER BATTERY BEARING BECAUSE BECOMES BEDROOM BELIEFS BELONGS BENEATH BENEFIT BESIDES BILLION BLANKET BLENDED BLESSED BLOCKED BLOOMED BLOSSOM BLUNDER BOASTED BOOKING BOROUGH BOTHERS BOULDER BOUNCED BRACKET BRAIDED BRANDED BREADTH BREATHE BRIDGES BRIEFLY BRISTLE BROADLY BROTHER BROUGHT BROWSER BRUSHED BUBBLES BUCKETS BUFFALO BUILDER BUILDUP BUNDLES BURDENS BURNING BUSTLED BUTCHER BUTTONS
CABINET CALCIUM CALIBER CALLING CAPABLE CAPITAL CAPTAIN CAPTURE CARAMEL CARDIAC CATERED CAUTION CEILING CENTRAL CENTURY CERTAIN CHAMBER CHANNEL CHAPTER CHARTER CHECKED CHERISH CHICKEN CHIMNEY CHOKING CHRONIC CIRCLES CIRCUIT CLAIMED CLASSIC CLEANED CLEANER CLIMATE CLIMBED CLINICS CLOSEST CLOSING CLOSURE CLUSTER COASTAL COATING COCKPIT COLLECT COLLIDE COLORED COLUMNS COMBINE COMFORT COMMAND COMMENT COMPACT COMPANY COMPARE COMPETE COMPILE COMPLEX COMPOSE COMPUTE COMRADE CONCEPT CONCERN CONDUCT CONFESS CONFIDE CONFINE CONFIRM CONNECT CONSENT CONSIST CONSOLE CONSULT CONTACT CONTAIN CONTENT CONTEST CONTEXT CONTROL CONVERT COOKING COOLERS CORRECT COUNCIL COUNTER COUNTRY COURAGE COVERED CRACKED CRADLES CRAFTED CRAMMED CRASHED CRAVING CREATED CREDITS CRESTED CRICKET CRITICS CROSSED CRUSHED CRUCIAL CRUISED CRUMBLE CRYSTAL CULTURE CUNNING CURATOR CURRENT CURTAIN CUSHION CUSTOMS
DAMAGES DAWNING DEALING DEBATED DECADES DECEIVE DECIDED DECLINE DECODED DECORUM DEEPEST DEFEATS DEFAULT DEFENSE DELAYED DELETED DELIGHT DELIVER DEMANDS DENSELY DEPOSIT DERIVED DESCENT DESERVE DESIRED DESKTOP DESPAIR DESPITE DESTROY DETAILS DEVELOP DEVOTED DIAGRAM DIAMOND DIGITAL DILEMMA DIPLOMA DIRECTS DISABLE DISCARD DISCUSS DISEASE DISGUST DISMISS DISPLAY DISPOSE DISPUTE DISTANT DIVERSE DIVIDED DONATED DOUBLED DOUBLES DRAFTED DRAGGED DRAINED DRAWING DRESSED DRIFTED DRIVERS DRIVING DROPPED DUBIOUS DYNAMIC DYNASTY
EAGERLY EARLIER EARNEST EASTERN ECLIPSE ECOLOGY ECONOMY EDITION EDITORS EDUCATE EFFECTS EFFORTS ELDERLY ELECTED ELEGANT ELEMENT ELEVATE EMBASSY EMBRACE EMERGED EMOTION EMPEROR EMPIRES EMPLOYS ENABLED ENCLOSE ENDLESS ENDORSE ENDURED ENFORCE ENGAGED ENGINES ENGLISH ENHANCE ENJOYED ENLARGE ENSURED ENTERED EPISODE EQUATOR ERECTED ESCAPED ESSENCE ESTATES ETERNAL EVENING EVIDENT EVOLVED EXACTLY EXAMINE EXAMPLE EXCEEDS EXCITED EXCLUDE EXCUSES EXECUTE EXHAUST EXHIBIT EXISTED EXPERTS EXPIRES EXPLAIN EXPLOIT EXPLORE EXPORTS EXPOSED EXTENDS EXTRACT EXTREME
FACTORY FACULTY FAILING FAILURE FASHION FASTEST FATIGUE FEATURE FEDERAL FEEDING FICTION FIFTEEN FIGHTER FIGURES FILLING FINALLY FINDING FINGERS FITNESS FLANKED FLASHED FLATTEN FLAVORS FLEEING FLICKER FLIGHTS FLOATED FLOODED FLOORED FLOWING FLUTTER FOCUSED FOLDERS FOLLOWS FOOLISH FOOTAGE FOREIGN FOREVER FORGING FORGIVE FORMULA FORTUNE FORWARD FOSSILS FOUNDED FOUNDER FRAGILE FRANTIC FREEDOM FREIGHT FRIENDS FULFILL FUNDING FURIOUS FURNACE FURTHER FUTURES
GALLERY GALLONS GARBAGE GARDENS GATEWAY GAZETTE GENERAL GENERIC GENUINE GESTURE GLACIER GLAMOUR GLIMPSE GLORIFY GLOWING GODDESS GOODBYE GRABBED GRADUAL GRAMMAR GRANITE GRANTED GRAPHIC GRASPED GREATLY GREETED GRIEVED GRILLED GROCERY GROUNDS GROWING GRUMBLE GUARDED GUITARS GUSHING
HABITAT HALFWAY HALTING HANDFUL HANDLED HANDLER HANGING HAPPILY HARBORS HARDEST HARMFUL HARMONY HARNESS HARVEST HASTILY HAUNTED HEALTHY HEARING HEAVILY HEIGHTS HELPFUL HELPING HERSELF HIGHWAY HIMSELF HISTORY HOLDING HOLIDAY HONORED HORIZON HOSTILE HOUSING HOWEVER HUDDLES HUNTING HURDLES HURRIED HUSBAND
ICEBERG IMAGINE IMMENSE IMPEACH IMPLIED IMPLIES IMPORTS IMPOSED IMPRESS IMPROVE IMPULSE INCLUDE INCOMES INDEXED INDOORS INDUCED INFLATE INFLICT INFORMS INITIAL INNINGS INQUIRE INSECTS INSIGHT INSPECT INSPIRE INSTALL INSTANT INSTEAD INSULTS INTEGER INTENSE INTERIM ISLANDS
JACKETS JANITOR JEWELRY JOINING JOINTLY JOURNAL JOURNEY JUSTICE JUSTIFY
KEEPERS KEEPING KERNELS KETCHUP KICKING KITCHEN KNEADED KNEELED KNIGHTS KNOCKED KNOWING
LABELED LACKING LADDERS LANDING LARGELY LASTING LATERAL LAUGHED LAUNDRY LAWYERS LEADERS LEADING LEARNED LEATHER LEAVING LECTURE LEGALLY LEISURE LENDING LENGTHS LENIENT LESSENS LESSONS LETTERS LIBERAL LICENSE LIMITED LINKING LIQUIDS LISTING LITERAL LOCALLY LOCATED LOCKING LODGING LOGICAL LONGEST LOOKING LOOSELY LOTTERY LOVABLE LOWERED LOYALTY
MACHINE MADNESS MAGICAL MAGNIFY MAILBOX MAJESTY MANAGER MANAGES MANDATE MANNERS MANSION MAPPING MARGINS MARINES MARRIED MASSIVE MASTERY MATTERS MAXIMUM MEANING MEASURE MEDICAL MEETING MEMBERS MEMENTO MENTION MERCURY MERGING MIDTERM MIGRATE MILITIA MILLION MINERAL MINIMAL MINIMUM MIRRORS MISSILE MISSING MISSION MISTAKE MIXTURE MOBILES MODULAR MONSTER MONTHLY MOONLIT MOORING MORNING MORTALS MOUNTED MOUNTED MOURNED MUDDLES MUSCLES MUSICAL MYSTERY
NARRATE NATIONS NATURAL NEAREST NEATEST NEGLECT NEITHER NERVOUS NETWORK NEUTRAL NOTABLE NOTHING NOTICED NOWHERE NUCLEAR NUMBERS
OBEYING OBJECTS OBLIGED OBSCURE OBSERVE OBVIOUS OCTOBER OFFENSE OFFERED OFFICER OFFSETS OMITTED ONGOING OPENING OPERATE OPTIONS ORGANIC ORIGINS OUTDOOR OUTLAST OUTLINE OUTLOOK OUTPUTS OUTSIDE OVERALL OVERLAP OVERSEE
PACKAGE PAINFUL PAINTED PALACES PALETTE PANICKY PARADES PARKING PARLORS PARTIAL PARTIES PARTNER PASSAGE PASSING PASSION PASSIVE PATIENT PATRIOT PATTERN PAYLOAD PAYMENT PAYROLL PEACOCK PEASANT PENALTY PENDING PENSION PERCENT PERFECT PERFORM PERIODS PERMITS PERSIST PERSONS PHYSICS PICTURE PIERCED PILGRIM PILLARS PILLOWS PIONEER PIVOTED PLACING PLANNED PLANNER PLANTED PLASTER PLASTIC PLATTER PLAYERS PLAYING PLEASED PLOTTED PLOWING PLUCKED PLUGGED PLUMBER PLUNGED PLUNDER POINTED POLICED POLITIC POLLING POLLUTE POPULAR PORTION PORTRAY POSSESS POSTING POSTMAN POTENCY POTTERY POURING POVERTY POWERED PRECISE PREDICT PREMIER PREPARE PRESENT PRESSED PRESUME PRETEND PREVENT PRICING PRIMARY PRIMING PRISONS PRIVACY PRIVATE PROBLEM PROCEED PROCESS PRODUCE PRODUCT PROFILE PROFITS PROGRAM PROJECT PROMISE PROMOTE PRONOUN PROPPED PROTECT PROTEST PROVIDE PROVOKE PRUDENT PUBLISH PULLING PUMPING PUNCHED PURSUED PUZZLED
QUALIFY QUARTER QUERIES QUICKLY QUIETLY QUILTED QUOTING
RADICAL RAINBOW RALLIED RAMPAGE RANCHER RANGING RANKING RAPIDLY READING REALITY REALIZE REASONS REBOUND REBUILD RECEIPT RECEIVE RECORDS RECOVER RECRUIT REFINED REFLECT REFORMS REFRESH REFUSED REGARDS REGIONS REGRETS REGULAR RELATED RELEASE REMAINS REMARKS REMOVAL REMOVED RENEWAL RENTALS REPAIRS REPEATS REPLACE REPLIED REPORTS REQUEST REQUIRE RESCUED RESERVE RESIDED RESOLVE RESORTS RESPECT RESPOND RESTORE RESULTS RESUMED RETIRED RETREAT RETURNS REUNION REVEALS REVENUE REVERSE REVISED REVOLVE REWARDS RICHEST RIDDLES RIVALRY ROASTED ROBBERY ROLLING ROMANCE ROOFTOP ROUTINE RUBBING RUBBISH RUMORED RUNNING RUPTURE RUSHING RUSTLED
SADNESS SAILORS SALVAGE SAMPLES SAVAGES SAVINGS SCANDAL SCARRED SCATTER SCENERY SCHEMES SCHOOLS SCIENCE SCORING SEASONS SEATING SECRECY SECRETS SECTION SECURED SEEKING SEGMENT SEIZING SELLERS SELLING SENDING SENIORS SERVING SESSION SETTLED SETTLER SEVENTY SEVERAL SEVERED SHELVED SHIFTED SHINING SHIPPED SHOCKED SHORTER SHORTLY SHOWERS SHOWING SIBLING SIGHTED SIGNALS SILENCE SIMILAR SINCERE SKILLED SLAMMED SLAVERY SLENDER SLICING SLIPPED SMALLER SMASHED SMOKING SNAPPED SOCIETY SOFTEST SOLDIER SOMEHOW SORTING SPARKED SPATIAL SPEAKER SPECIAL SPECIES SPECIFY SPONSOR SPOTTED SPRAYED SPRINGS SQUARED SQUEEZE STACKED STAGING STAINED STALLED STAMPED STAPLES STARING STARTED STARTER STATING STATION STATUES STAYING STEALTH STEAMER STEELED STEPPED STOPPER STOPPED STORAGE STREAMS STRETCH STRIPED STUDIES STUNNED SUBDUED SUBJECT SUBMITS SUCCEED SUCCESS SUGGEST SUMMARY SUMMITS SUNRISE SUPREME SURFACE SURGEON SURPLUS SURVIVE SUSPECT SUSPEND SYMBOLS SYSTEMS
TABLETS TACTICS TAKEOFF TALENTS TALKING TANGLES TARGETS TEACHER TEMPTED TENSION TERRAIN TESTING TEXTURE THEATER THERAPY THEREBY THINKER THOUGHT THREADS THREATS THROUGH THUNDER TICKETS TIGHTEN TOBACCO TONIGHT TOPPLED TORMENT TOTALLY TOUCHED TOURISM TOURIST TOWARDS TRACKED TRACKER TRADING TRAFFIC TRAINED TRAINER TRANSIT TRAPPED TRAVELS TREATED TREMBLE TRIBUTE TRICKED TRIGGER TRILOGY TRIMMED TRIUMPH TROUBLE TRUSTED TUNNELS TURMOIL TURNING TURTLES TWISTED TYPICAL
UMPTEEN UNAWARE UNDERGO UNICORN UNIFIED UNIFORM UNKNOWN UNLEASH UNLUCKY UPDATED UPGRADE UPRIGHT UPROARS UPSCALE UPSWING USUALLY UTTERED UTTERLY
VACANCY VACCINE VALLEYS VAMPIRE VANILLA VARIETY VEHICLE VENTURE VERDICT VETERAN VICTIMS VICTORY VILLAGE VILLAIN VINTAGE VIOLENT VIRTUAL VISITED VISITOR VOLCANO VOLUMES
WAGERED WAITING WALKING WANTING WARDENS WARNING WARPING WARRIOR WASTING WATCHED WATCHES WEALTHY WEAPONS WEARING WEATHER WEDDING WEEKEND WEIGHED WELCOME WELFARE WESTERN WHISKEY WHISPER WHISTLE WINDING WINNING WINTERY WISHING WITNESS WIZARDS WONDERS WORKERS WORKING WORKOUT WRAPPER WRECKED WRITING WRITTEN
YIELDED YOUNGER ZEALOUS
""".split()
for w in common_text:
    w = w.strip().upper()
    if w.isalpha() and 3 <= len(w) <= 7:
        COMMON.add(w)

print(f"Common words: {len(COMMON)}")

words_by_len = defaultdict(list)
for w in all_words:
    words_by_len[len(w)].append(w)

# Pre-index
word_index = defaultdict(set)
for n, wlist in words_by_len.items():
    for w in wlist:
        for i, ch in enumerate(w):
            word_index[(n, i, ch)].add(w)

# Crossing map
cell_to_slots = defaultdict(list)
for i, (d, cells) in enumerate(slots):
    for j, (r, c) in enumerate(cells):
        cell_to_slots[(r,c)].append((i, j))

crossings = defaultdict(list)
for i, (d, cells) in enumerate(slots):
    for j, (r, c) in enumerate(cells):
        for other_idx, other_pos in cell_to_slots[(r,c)]:
            if other_idx != i:
                crossings[i].append((j, other_idx, other_pos))

best_solution = None
best_common_count = 0

def run_solver(seed):
    global best_solution, best_common_count
    random.seed(seed)
    grid = {}
    used_words = set()
    slot_assignment = [None] * len(slots)

    def get_candidates(slot_idx):
        _, cells = slots[slot_idx]
        n = len(cells)
        candidates = None
        for j, (r, c) in enumerate(cells):
            if (r, c) in grid:
                letter = grid[(r, c)]
                key = (n, j, letter)
                matching = word_index.get(key, set())
                if candidates is None:
                    candidates = set(matching)
                else:
                    candidates &= matching
        if candidates is None:
            candidates = set(words_by_len[n])
        candidates -= used_words
        return list(candidates)

    def solve():
        filled = sum(1 for s in slot_assignment if s is not None)
        if filled == len(slots):
            return True
        best_s = None
        best_c = float('inf')
        best_cands = None
        for i in range(len(slots)):
            if slot_assignment[i] is not None: continue
            cands = get_candidates(i)
            if not cands: return False
            if len(cands) < best_c:
                best_c = len(cands)
                best_s = i
                best_cands = cands
                if best_c == 1: break

        random.shuffle(best_cands)
        best_cands.sort(key=lambda w: 0 if w in COMMON else 1)

        for word in best_cands:
            _, cells = slots[best_s]
            old_grid = {}
            for j, (r, c) in enumerate(cells):
                old_grid[(r,c)] = grid.get((r,c))
                grid[(r,c)] = word[j]
            slot_assignment[best_s] = word
            used_words.add(word)

            valid = True
            for my_pos, other_idx, other_pos in crossings[best_s]:
                if slot_assignment[other_idx] is not None: continue
                letter = word[my_pos]
                other_len = len(slots[other_idx][1])
                key = (other_len, other_pos, letter)
                if key not in word_index:
                    valid = False; break
                has_any = False
                for ow in word_index[key]:
                    if ow in used_words: continue
                    ok = True
                    for oj, (or_, oc) in enumerate(slots[other_idx][1]):
                        if (or_, oc) in grid and grid[(or_, oc)] != ow[oj]:
                            ok = False; break
                    if ok: has_any = True; break
                if not has_any:
                    valid = False; break

            if valid and solve():
                return True

            used_words.discard(word)
            slot_assignment[best_s] = None
            for (r,c), v in old_grid.items():
                if v is None:
                    if (r,c) in grid: del grid[(r,c)]
                else: grid[(r,c)] = v
        return False

    import signal
    signal.signal(signal.SIGALRM, lambda s, f: (_ for _ in ()).throw(KeyboardInterrupt))
    signal.alarm(15)
    try:
        if solve():
            words = [slot_assignment[i] for i in range(len(slots))]
            c_count = sum(1 for w in words if w in COMMON)
            if c_count > best_common_count:
                best_common_count = c_count
                best_solution = (dict(grid), list(words), [s for s in slots])
            return c_count
    except KeyboardInterrupt:
        return -1
    finally:
        signal.alarm(0)
    return -2

# Search for best solution
print("\nSearching for best solution...")
for seed in range(50):
    t0 = time.time()
    result = run_solver(seed)
    elapsed = time.time() - t0
    if result > 0:
        print(f"  Seed {seed:2d}: {result}/78 common ({elapsed:.1f}s) {'*** BEST' if result == best_common_count else ''}")
    elif result == -1:
        pass  # timeout, skip printing
    if best_common_count >= 70:
        break

if not best_solution:
    print("No solution found")
    sys.exit(1)

grid_d, words, slot_list = best_solution
print(f"\nBest solution: {best_common_count}/78 common words")

# Build grid 2D
grid_2d = []
for r in range(15):
    row = []
    for c in range(15):
        if PATTERN[r][c] == '#':
            row.append('#')
        else:
            row.append(grid_d.get((r,c), '?'))
    grid_2d.append(row)

# Print grid
print("\nGrid:")
for r in range(15):
    print("  " + " ".join(grid_2d[r]))

# Identify non-common words
non_common = [w for w in words if w not in COMMON]
print(f"\nNon-common words ({len(non_common)}):")
for w in sorted(set(non_common)):
    print(f"  {w}")

# Assign clue numbers and extract word info
print("\n=== CLUE NUMBER ASSIGNMENT ===")
clue_num = 0
across_clues = []
down_clues = []
numbered = {}

for r in range(15):
    for c in range(15):
        if PATTERN[r][c] == '#':
            continue
        is_a = False
        is_d = False
        # Check if this starts an across word
        if (c == 0 or PATTERN[r][c-1] == '#'):
            # Count length
            length = 0
            cc = c
            while cc < 15 and PATTERN[r][cc] != '#':
                length += 1
                cc += 1
            if length >= 3:
                is_a = True
        # Check if this starts a down word
        if (r == 0 or PATTERN[r-1][c] == '#'):
            length = 0
            rr = r
            while rr < 15 and PATTERN[rr][c] != '#':
                length += 1
                rr += 1
            if length >= 3:
                is_d = True

        if is_a or is_d:
            clue_num += 1
            numbered[(r,c)] = clue_num
            if is_a:
                word = ""
                cc = c
                while cc < 15 and PATTERN[r][cc] != '#':
                    word += grid_2d[r][cc]
                    cc += 1
                across_clues.append({"number": clue_num, "answer": word, "row": r, "col": c})
            if is_d:
                word = ""
                rr = r
                while rr < 15 and PATTERN[rr][c] != '#':
                    word += grid_2d[rr][c]
                    rr += 1
                down_clues.append({"number": clue_num, "answer": word, "row": r, "col": c})

print(f"Total clue numbers: {clue_num}")
print(f"Across clues: {len(across_clues)}")
print(f"Down clues: {len(down_clues)}")

# Verify sequential numbering
nums = sorted(set(e["number"] for e in across_clues + down_clues))
expected = list(range(1, len(nums)+1))
assert nums == expected, f"Non-sequential: {nums}"

# Print all words with numbers
print("\nACROSS:")
for e in across_clues:
    mark = "" if e["answer"] in COMMON else " *"
    print(f"  {e['number']:2d}. {e['answer']}{mark}")

print("\nDOWN:")
for e in down_clues:
    mark = "" if e["answer"] in COMMON else " *"
    print(f"  {e['number']:2d}. {e['answer']}{mark}")

# Save for clue writing
with open("/tmp/puzzle_words.json", "w") as f:
    json.dump({"across": across_clues, "down": down_clues, "grid": grid_2d}, f, indent=2)
print("\nSaved to /tmp/puzzle_words.json")
